#!/usr/bin/env python

""" get  APO-local STUI scripts library from svn

run independently from any other scripts
dd='svn+ssh://sdss3svn@sdss3.org/repo/apo/Scripts/trunk'
dd='svn+ssh://sdss3svn@sdss3.org/repo/apo/Scripts/tags/v4_1/'
svn export ${dd}

08-22-2013 EM 
"""

import optparse

import os
import shutil

desc = 'getting APO-local scripts from svn '
usage = ' %(prog)s [OPTIONS]'
parser = optparse.OptionParser(description=desc, usage=usage)
parser.add_option('-v', '--version', help="get version as v4_1, default trunk", \
                  default="trunk", type='string', action='store')

(opts, args) = parser.parse_args()
ver = opts.version
origdir = os.getcwd()
dirname = "%s/%s" % (origdir, ver)
if os.path.isdir(dirname):
    print "  deleting  old script directory .. ",
    shutil.rmtree(dirname)
    print "done"

svnpath = "svn+ssh://sdss3svn@sdss3.org/repo/apo/Scripts/"
if ver != "trunk":
    ver = "tags/%s/" % ver
svnpath = svnpath + ver
print "  creating new directory and copying files ...",
cmd = "svn export %s" % svnpath
os.system(cmd)
print "done"

# dd="svn+ssh://sdss3svn@sdss3.org/repo/apo/Scripts/trunk"
# dd="svn+ssh://sdss3svn@sdss3.org/repo/apo/Scripts/tags/v4_1/"
# svn export ${dd}
